// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir1org} from '../models';

export function AtualizarCache():Promise<string>;

export function ListarDiretorios():Promise<Array<string>>;

export function PlayTrack():Promise<void>;

export function RetornandoLista():Promise<Array<dir1org.ListaMusicas>>;

export function TogglePause():Promise<void>;
