// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AtualizarCache() {
  return window['go']['main']['App']['AtualizarCache']();
}

export function ListarDiretorios() {
  return window['go']['main']['App']['ListarDiretorios']();
}

export function PlayTrack() {
  return window['go']['main']['App']['PlayTrack']();
}

export function RetornandoLista() {
  return window['go']['main']['App']['RetornandoLista']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
