// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PlayTrack() {
  return window['go']['main']['App']['PlayTrack']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
