// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dir1org} from '../models';

export function Creates_list():Promise<Array<dir1org.ListaMusicas>>;

export function PlayTrack():Promise<void>;

export function TogglePause():Promise<void>;
